name: Build CIS-Hardened AMI

on:
  workflow_dispatch

jobs:
  build-ami:
    name: Build CIS-Hardened AMI
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Packer
        uses: hashicorp/setup-packer@v2
        with:
          packer_version: latest


      - name: Install AWS CLI
        run: |
          sudo apt install -y awscli

      - name: Configure AWS CLI
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ secrets.AWS_REGION }}
        run: |
          aws configure set aws_access_key_id $AWS_ACCESS_KEY_ID
          aws configure set aws_secret_access_key $AWS_SECRET_ACCESS_KEY
          aws configure set default.region $AWS_REGION

      - name: Validate Packer Template
        run: |
          packer validate -var-file=variables.json cis-ami.pkr.hcl

      - name: Capture AMI Metadata
        id: ami_metadata
        run: |
          AMI_ID=$(packer build -var-file=variables.json -machine-readable cis-ami.pkr.hcl | awk -F, '$0 ~/artifact,0,id/ {print $6}')
          echo "AMI_ID=${AMI_ID}" >> $GITHUB_ENV
          echo "AMI_ID is $AMI_ID"

      - name: Display AMI Metadata
        if: success()
        run: |
          echo "The AMI ID is ${{ env.AMI_ID }}"

      - name: Get Full AMI Metadata
        if: success()
        run: |
          aws ec2 describe-images --image-ids ${{ env.AMI_ID }} --query 'Images[0]'

      - name: Success Notification
        if: success()
        run: |
          echo "AMI Built Successfully with AMI ID: ${{ env.AMI_ID }}"
